// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soymkgjjwqmmcmkicwbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNveW1rZ2pqd3FtbWNta2ljd2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzg3NDEsImV4cCI6MjA2NTgxNDc0MX0.v-i79fQTNT29WZpMVIEJuIvaCygjnog6nf_22IWeXh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);